### PR TITLE
will fix prevent adding shows on recomended pages if no root dir set

### LINKED ISSUE #2214: Adding show from recommend shows without root directory configured...
... causes warning in logs but still shows ADDED 

### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Develop
**OS:** Win 10
**What you did:**  On fresh install with no root directory configured yet, go to Add From Recommended and add a show
**What happened:**  Series shows as added but show does not get added to the show list.
**What you expected:**  Prompt to configure a root directory before allowing show selection or at least a visible warning that show failed to add.  Currently only warning is from warning pill which does not update until after a new page load.
**Logs:**
```
NOT APPLICABLE
```

### PR DESCRIPTION
**Pull request by Thraxis**
- disables 'add' buttons
- shows alert at top of page
- opens custom settings to add root directories
- clears alert and re-enables buttons when directory added
- fixes #2214

image

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

@labrys

### CODE REVIEW

**Comment by fernandog** [comment]
@Thraxis maybe we need to handle adding shows using API when no root folder. agree?

**Comment by Thraxis** [comment]
APIv1 already checks and returns an error message if the root directory isn't set:
https://github.com/pymedusa/Medusa/blob/9503765ab2450bce1c4e3bfb1f346947a4a965cf/medusa/server/api/v1/core.py#L2043-L2050

APIv2 doesn't currently support adding a show:
https://github.com/pymedusa/Medusa/blob/9503765ab2450bce1c4e3bfb1f346947a4a965cf/medusa/server/api/v2/show.py#L186-L188

**Comment by fernandog** [comment]
@Thraxis can you do a test?

remove git location so it shows `Unable to find your git executable - Shutdown the application and EITHER set git_path in your config.ini OR delete your .git folder and run from source to enable updates.`

remove root folder. the git warning disappears.

**Comment by Thraxis** [comment]
@fernandog I'm not sure how the test you want me to do relates to this PR

**Comment by fernandog** [comment]
@Thraxis i thinking that the root folder warning message is conflicting with the git message.

**Comment by Thraxis** [comment]
Do not merge, pending a review of the disappearing git alert

File: static/js/add-shows/init.js [hunk 1]
```diff
@@ -44,6 +44,26 @@ MEDUSA.addShows.init = function() {
             });
         });
 
+        $('#rootDirs').on('change', function() {
+            if ($('#rootDirs option:selected').length === 0) {
+                $('button[data-add-show]').prop('disabled', true);
+                if (!$('#configure_show_options').is(':checked')) {
+                    $('#configure_show_options').trigger('click');
```
Comment (OmgImAlexis) [inline static/js/add-shows/init.js]: Why are you triggering a check when you could just run whatever the click event should?

File: static/js/add-shows/recommended-shows.js [hunk 2]
```diff
@@ -10,6 +10,22 @@ MEDUSA.addShows.recommendedShows = function() {
     $.initAddShowById();
     $.initBlackListShowById();
     $.initRemoteShowGrid();
-    $.imgLazyLoad.update();
-    $.imgLazyLoad.handleScroll();
+
+    if ($('#rootDirs option:selected').length === 0) {
```
Comment (OmgImAlexis) [inline static/js/add-shows/recommended-shows.js]: Please stop duplicating functions. If a function is used on multiple pages it needs to be added to the common file. I've said this multiple times.

File: static/js/root-dirs.js [hunk 3]
```diff
@@ -58,6 +58,7 @@ $(document).ready(function() {
 
     function refreshRootDirs() {
         if ($('#rootDirs').length === 0) {
+            $('#rootDirs').trigger('change');
```
Comment (OmgImAlexis) [inline static/js/root-dirs.js]: Why are you triggering change? Just call the function..

File: static/js/root-dirs.js [hunk 4]
```diff
@@ -96,7 +97,8 @@ $(document).ready(function() {
         console.log(logString);
 
         $('#rootDirText').val(dirString);
-        $('#rootDirText').change();
+        $('#rootDirText').change(); // Not triggering?
```
Comment (OmgImAlexis) [inline static/js/root-dirs.js]: Again.

File: static/js/root-dirs.js [hunk 5]
```diff
@@ -96,7 +97,8 @@ $(document).ready(function() {
         console.log(logString);
```
Comment (OmgImAlexis) [inline static/js/root-dirs.js]: Remove logs.

**Comment by fernandog** [comment]
@thraxis why did you close? It was a very nice OR

**Comment by fernandog** [comment]
@Thraxis may i continue?

**Comment by fernandog** [comment]
@Thraxis can we reopen this please?

**Comment by Thraxis** [comment]
Well that rebase went horribly wrong

File: static/js/add-shows/recommended-shows.js [hunk 6]
```diff
@@ -10,6 +10,5 @@ MEDUSA.addShows.recommendedShows = function() {
     $.initAddShowById();
     $.initBlackListShowById();
     $.initRemoteShowGrid();
-    $.imgLazyLoad.update();
-    $.imgLazyLoad.handleScroll();
```
Comment (fernandog) [inline static/js/add-shows/recommended-shows.js]: @thraxis is this supposed to be removed?

Comment (Thraxis) [inline static/js/add-shows/recommended-shows.js]: Yes they were removed because they don't actually work there

**Comment by fernandog** [comment]
@Thraxis 

image

**Comment by fernandog** [comment]
@Thraxis 

https://cloud.githubusercontent.com/assets/2620870/23586892/daeca27e-017d-11e7-87a2-d69048c6d739.png

**Comment by fernandog** [comment]
it will only show the alert when user removes it?
If I start medusa without a root folder, will the alert be visible?

**Comment by Thraxis** [comment]
Add new show has no need for an alert as step 2 is "pick a directory" and it will not allow you to submit without having selected a root directory.

The alert and disable of adding is for the add from Trakt, IMDB and Anidb lists.

**Comment by fernandog** [comment]
@Thraxis disappearing git alert also happens in devleop. so will merge this
